[View in Colaboratory](https://colab.research.google.com/github/ditiansm2015/ML-May-28/blob/master/assignment_4.ipynb)

SUDHANSHU MISHRA

Machine Learning with Python (SUM18 ML ON1)

ASSIGNMENT_4

In [69]:
#Question 1
#Create a dataframe with your name , age , mail id and phone 
#number and add your friendsâ€™s information to the same.


import pandas as pd

#Creating our own dataset using python dictionary
record={'NAME':['Sudhanshu','Rahul'],'AGE':[21,19],'MAIL ID':['ditiansm2015@gmail.com','rahul1212@gmail.com'],'PHONE':[9454764310,8576892748]}

#DataFrame() creates a dataframe(table) comprising all the elements of dictionary
df=pd.DataFrame(record)


#setting the order for columns in which they should appear else they would be set in random fashion
df = df[['NAME', 'AGE', 'MAIL ID','PHONE']]

print("Before adding new records:\n",df,"\n\n")

#Appending 2 more rows/records to the dataframe
df.loc[2] = ['Shreyas', 72, 'shreyas3108@gmail.com',8548754687]
df.loc[3] = ['Himanshu',56, 'himanshu205@gmail.com',8548724787]


#df.append({'NAME':['Shreyas'], 'AGE':[72],'MAIL ID':['shreyas3108@gmail.com'],'PHONE':[8858745877]},ignore_index=True)

print("After adding new records:\n",df,"\n\n")

Before adding new records:
         NAME  AGE                 MAIL ID       PHONE
0  Sudhanshu   21  ditiansm2015@gmail.com  9454764310
1      Rahul   19     rahul1212@gmail.com  8576892748


After adding new records:
         NAME  AGE                 MAIL ID       PHONE
0  Sudhanshu   21  ditiansm2015@gmail.com  9454764310
1      Rahul   19     rahul1212@gmail.com  8576892748
2    Shreyas   72   shreyas3108@gmail.com  8548754687
3   Himanshu   56   himanshu205@gmail.com  8548724787

In [70]:
#Question 2
#Download the dataset from this link :
#https://raw.githubusercontent.com/Shreyas3108/Weather/master/weather.csv
 
#Import the data and print the following :
#a.) First 5 rows of Dataframe 
#b.) First 10 rows of the Dataframe 
#c.) find basic statistics on the particular dataset. 
#d.) Find the last 5 rows of the dataframe 
#e.) Extract the 2nd column and find basic statistics on it.


import pandas as pd

#Reading CSV file from the given link
df=pd.read_csv("https://raw.githubusercontent.com/Shreyas3108/Weather/master/weather.csv")

#Printing first five rows of dataframe(no argument inside head() automatically prsents first 5 rows)
firstFiveRows=df.head()
print("\nFirst Five Rows are:\n\n",firstFiveRows)

print("\n\n------------------------------------------------------------------\n\n")

#Printing first ten rows of dataframe(head(n) gives first n rows of dataframe)
firstTenRows=df.head(10)
print("\n\nFirst Ten Rows are:\n\n",firstTenRows)

print("\n\n------------------------------------------------------------------\n\n")

#Basic statistics of dataframe(describe()gives complete detail of the dataset)
statistics=df.describe(include="all")
print("\n\nStatistics of the dataset:\n\n",statistics)

print("\n\n------------------------------------------------------------------\n\n")

#Last five rows of dataframe
lastFiveRows=df.tail()
print("\n\nLast Five Rows are:\n\n",lastFiveRows)

print("\n\n------------------------------------------------------------------\n\n")

#Statistics of Second column
secColStats=df['Location'].describe(include='all')
print("\n\nSecond Column Statistics:\n\n",secColStats)

First Five Rows are:

         Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  11/1/2007  Canberra      8.0     24.3       0.0          3.4       6.3
1  11/2/2007  Canberra     14.0     26.9       3.6          4.4       9.7
2  11/3/2007  Canberra     13.7     23.4       3.6          5.8       3.3
3  11/4/2007  Canberra     13.3     15.5      39.8          7.2       9.1
4  11/5/2007  Canberra      7.6     16.1       2.8          5.6      10.6

  WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
0          NW           30.0         SW      ...               29
1         ENE           39.0          E      ...               36
2          NW           85.0          N      ...               69
3          NW           54.0        WNW      ...               56
4         SSE           50.0        SSE      ...               49

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1019.7       1015.0         7         7     14.4     23.6         No
1       1012.4       1008.4         5         3     17.5     25.7        Yes
2       1009.5       1007.2         8         7     15.4     20.2        Yes
3       1005.5       1007.0         2         7     13.5     14.1        Yes
4       1018.3       1018.5         7         7     11.1     15.4        Yes

   RISK_MM  RainTomorrow
0      3.6           Yes
1      3.6           Yes
2     39.8           Yes
3      2.8           Yes
4      0.0            No

[5 rows x 24 columns]


------------------------------------------------------------------




First Ten Rows are:

          Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0   11/1/2007  Canberra      8.0     24.3       0.0          3.4       6.3
1   11/2/2007  Canberra     14.0     26.9       3.6          4.4       9.7
2   11/3/2007  Canberra     13.7     23.4       3.6          5.8       3.3
3   11/4/2007  Canberra     13.3     15.5      39.8          7.2       9.1
4   11/5/2007  Canberra      7.6     16.1       2.8          5.6      10.6
5   11/6/2007  Canberra      6.2     16.9       0.0          5.8       8.2
6   11/7/2007  Canberra      6.1     18.2       0.2          4.2       8.4
7   11/8/2007  Canberra      8.3     17.0       0.0          5.6       4.6
8   11/9/2007  Canberra      8.8     19.5       0.0          4.0       4.1
9  11/10/2007  Canberra      8.4     22.8      16.2          5.4       7.7

  WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
0          NW           30.0         SW      ...               29
1         ENE           39.0          E      ...               36
2          NW           85.0          N      ...               69
3          NW           54.0        WNW      ...               56
4         SSE           50.0        SSE      ...               49
5          SE           44.0         SE      ...               57
6          SE           43.0         SE      ...               47
7           E           41.0         SE      ...               57
8           S           48.0          E      ...               48
9           E           31.0          S      ...               32

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1019.7       1015.0         7         7     14.4     23.6         No
1       1012.4       1008.4         5         3     17.5     25.7        Yes
2       1009.5       1007.2         8         7     15.4     20.2        Yes
3       1005.5       1007.0         2         7     13.5     14.1        Yes
4       1018.3       1018.5         7         7     11.1     15.4        Yes
5       1023.8       1021.7         7         5     10.9     14.8         No
6       1024.6       1022.2         4         6     12.4     17.3         No
7       1026.2       1024.2         6         7     12.1     15.5         No
8       1026.1       1022.7         7         7     14.1     18.9         No
9       1024.1       1020.7         7         1     13.3     21.7        Yes

   RISK_MM  RainTomorrow
0      3.6           Yes
1      3.6           Yes
2     39.8           Yes
3      2.8           Yes
4      0.0            No
5      0.2            No
6      0.0            No
7      0.0            No
8     16.2           Yes
9      0.0            No

[10 rows x 24 columns]


------------------------------------------------------------------




Statistics of the dataset:

             Date  Location     MinTemp     MaxTemp    Rainfall  Evaporation  \
count        366       366  366.000000  366.000000  366.000000   366.000000
unique       366         1         NaN         NaN         NaN          NaN
top     1/3/2008  Canberra         NaN         NaN         NaN          NaN
freq           1       366         NaN         NaN         NaN          NaN
mean         NaN       NaN    7.265574   20.550273    1.428415     4.521858
std          NaN       NaN    6.025800    6.690516    4.225800     2.669383
min          NaN       NaN   -5.300000    7.600000    0.000000     0.200000
25%          NaN       NaN    2.300000   15.025000    0.000000     2.200000
50%          NaN       NaN    7.450000   19.650000    0.000000     4.200000
75%          NaN       NaN   12.500000   25.500000    0.200000     6.400000
max          NaN       NaN   20.900000   35.800000   39.800000    13.800000

          Sunshine WindGustDir  WindGustSpeed WindDir9am      ...       \
count   363.000000         363     364.000000        335      ...
unique         NaN          16            NaN         16      ...
top            NaN          NW            NaN         SE      ...
freq           NaN          73            NaN         47      ...
mean      7.909366         NaN      39.840659        NaN      ...
std       3.481517         NaN      13.059807        NaN      ...
min       0.000000         NaN      13.000000        NaN      ...
25%       5.950000         NaN      31.000000        NaN      ...
50%       8.600000         NaN      39.000000        NaN      ...
75%      10.500000         NaN      46.000000        NaN      ...
max      13.600000         NaN      98.000000        NaN      ...

       Humidity3pm  Pressure9am  Pressure3pm    Cloud9am    Cloud3pm  \
count   366.000000   366.000000   366.000000  366.000000  366.000000
unique         NaN          NaN          NaN         NaN         NaN
top            NaN          NaN          NaN         NaN         NaN
freq           NaN          NaN          NaN         NaN         NaN
mean     44.519126  1019.709016  1016.810383    3.890710    4.024590
std      16.850947     6.686212     6.469422    2.956131    2.666268
min      13.000000   996.500000   996.800000    0.000000    0.000000
25%      32.250000  1015.350000  1012.800000    1.000000    1.000000
50%      43.000000  1020.150000  1017.400000    3.500000    4.000000
75%      55.000000  1024.475000  1021.475000    7.000000    7.000000
max      96.000000  1035.700000  1033.200000    8.000000    8.000000

           Temp9am     Temp3pm  RainToday     RISK_MM  RainTomorrow
count   366.000000  366.000000        366  366.000000           366
unique         NaN         NaN          2         NaN             2
top            NaN         NaN         No         NaN            No
freq           NaN         NaN        300         NaN           300
mean     12.358470   19.230874        NaN    1.428415           NaN
std       5.630832    6.640346        NaN    4.225800           NaN
min       0.100000    5.100000        NaN    0.000000           NaN
25%       7.625000   14.150000        NaN    0.000000           NaN
50%      12.550000   18.550000        NaN    0.000000           NaN
75%      17.000000   24.000000        NaN    0.200000           NaN
max      24.700000   34.500000        NaN   39.800000           NaN

[11 rows x 24 columns]


------------------------------------------------------------------




Last Five Rows are:

            Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
361  10/27/2008  Canberra      9.0     30.7       0.0          7.6      12.1
362  10/28/2008  Canberra      7.1     28.4       0.0         11.6      12.7
363  10/29/2008  Canberra     12.5     19.9       0.0          8.4       5.3
364  10/30/2008  Canberra     12.5     26.9       0.0          5.0       7.1
365  10/31/2008  Canberra     12.3     30.2       0.0          6.0      12.6

    WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
361         NNW           76.0        SSE      ...               15
362           N           48.0        NNW      ...               22
363         ESE           43.0        ENE      ...               47
364          NW           46.0        SSW      ...               39
365          NW           78.0         NW      ...               13

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
361       1016.1       1010.8         1         3     20.4     30.0
362       1020.0       1016.9         0         1     17.2     28.2
363       1024.0       1022.8         3         2     14.5     18.3
364       1021.0       1016.2         6         7     15.8     25.9
365       1009.6       1009.2         1         1     23.8     28.6

     RainToday  RISK_MM  RainTomorrow
361         No      0.0            No
362         No      0.0            No
363         No      0.0            No
364         No      0.0            No
365         No      0.0            No

[5 rows x 24 columns]


------------------------------------------------------------------




Second Column Statistics:

 count          366
unique           1
top       Canberra
freq           366
Name: Location, dtype: object